modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Vazkii/Psi"

[[mods]]
modId="psi"
displayName="Psi"
version="${version}"
license="https://psi.vazkii.net/license.php"
authors="Vazkii, Wiiv, WireSegal, Kamefrede, Williewillus"
description='''
Psionic Spellcasting Instruments
'''
[[dependencies.psi]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16-39,)"
    side="BOTH"


[[dependencies.psi]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.108,)"
    ordering="AFTER"
    side="BOTH"